name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      # Install all dependencies
      - name: Install dependencies
        run: |
          npm ci
          cd packages/core && npm ci

      # Check TypeScript types
      - name: Run type check
        run: |
          cd packages/core
          npm run type-check

      # Run all tests
      - name: Run tests
        run: |
          cd packages/core
          npm run test:run

      # Build the library
      - name: Build library
        run: |
          cd packages/core
          npm run build

      # Verify build output
      - name: Check build artifacts
        run: |
          cd packages/core
          ls -la dist/

  demo-test:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"

      # Install dependencies for all workspaces
      - name: Install dependencies
        run: |
          npm ci
          cd packages/core && npm ci
          cd ../../apps/demo && npm ci

      # Build core library first
      - name: Build core library
        run: |
          cd packages/core
          npm run build

      # Build demo application
      - name: Build demo app
        run: |
          cd apps/demo
          npm run build
