name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  basic-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"

      # Install all dependencies
      - name: Install dependencies
        run: |
          npm ci
          cd packages/core && npm ci

      # Check TypeScript types only
      - name: Run type check
        run: |
          cd packages/core
          npm run type-check
