name: Quality Check

on:
  pull_request:
    branches: [main, develop]

jobs:
  quality-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"

      - name: Install root dependencies
        run: npm ci

      - name: Clean core dependencies
        working-directory: packages/core
        run: rm -rf node_modules package-lock.json

      - name: Install core dependencies
        working-directory: packages/core
        run: npm install

      - name: Run type check
        working-directory: packages/core
        run: npm run type-check

      - name: Build check
        working-directory: packages/core
        run: npm run build

      - name: Run tests
        working-directory: packages/core
        run: npm run test:run

      - name: Package check
        working-directory: packages/core
        run: npm pack --dry-run
