name: Quality Check

on:
  pull_request:
    branches: [main, develop]
  push:
    branches: [main, develop]

jobs:
  quality-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"

      # Install all dependencies
      - name: Install dependencies
        run: |
          npm ci
          cd packages/core && npm ci

      # Type checking
      - name: Run type check
        run: |
          cd packages/core
          npm run type-check

      # Build check
      - name: Build check
        run: |
          cd packages/core
          npm run build

      # Run tests
      - name: Run tests
        run: |
          cd packages/core
          npm run test:run

      # Package check
      - name: Package check
        run: |
          cd packages/core
          npm pack --dry-run
